kind: ServiceAccount
apiVersion: v1
metadata:
  name: simple-fastapi-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: simple-fastapi-role
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simple-fastapi-binding
subjects:
  - kind: ServiceAccount
    name: simple-fastapi-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: simple-fastapi-role
  apiGroup: rbac.authorization.k8s.io